"""empty message

Revision ID: 3244f196131d
Revises: 5f50c667bf04
Create Date: 2023-03-02 15:41:00.801216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3244f196131d'
down_revision = '5f50c667bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=700),
               nullable=False)
        batch_op.alter_column('process',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.alter_column('process',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=700),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
